server:
  name: admin
  port: 8189
  servlet:
    context-path: /admin

spring:
  profiles:
    active: dev
  servlet:
    # 文件上传
    multipart:
      enabled: true
      # 单个文件大小
      max-file-size: 500MB
      # 设置总上传的文件大小
      max-request-size: 500MB
  resources:
    static-locations: classpath:/static/
  # 关闭spring 启动动画
  main:
    banner-mode: off

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30
  #距离令牌到期多久续期(默认10分钟)
  alarmTime: 10
  # 是否支持多端登录(true:允许 false:不允许),默认允许
  concurrent: true
  # 多端登录最大在线个数(如果concurrent为false，max_user将失效)
  concurrentMax: 5
  # 密码错误次数
  pwd-error-max: 5
  # 密码错误时间范围（单位分钟）
  pwd-error-time: 10
  # 密码错误锁定时间（单位分钟）
  pwd-error-lock-time: 10

