server:
  name: admin
  port: 8188
  servlet:
    context-path: /admin

spring:
  profiles:
    active: dev
  servlet:
    # 文件上传
    multipart:
      enabled: true
      # 单个文件大小
      max-file-size: 500MB
      # 设置总上传的文件大小
      max-request-size: 500MB
  resources:
    static-locations: classpath:/static/

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30
  #距离令牌到期多久续期(默认20分钟)
  alarmTime: 20
