
# 日志文件配置
log:
  path: D:\dcsm\ #window系统日志文件路径/linux统日志文件路径


# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30
  #距离令牌到期多久续期(默认20分钟)
  alarmTime: 20