server:
  name: admin
  port: 8188
  servlet:
    context-path: /admin

spring:
  profiles:
    active: dev
  servlet:
    # 文件上传
    multipart:
      enabled: true
      # 单个文件大小
      max-file-size: 500MB
      # 设置总上传的文件大小
      max-request-size: 500MB
  resources:
    static-locations: classpath:/static/

# 详细配置文档：https://sa-token.cc/doc.html#/use/config
sa-token:
  # token名称
  token-name: admin-token
  # token风格
  token-style: simple-uuid
  # 是否允许同一账号并发登录
  is-concurrent: false
  # 打印banner
  is-print: false
#  # 是否尝试从请求体里读取token
#  is-read-body: false
#  # 是否尝试从cookie里读取token
#  is-read-cookie: false

  # token 有效期，单位=秒；默认30天，-1代表永不过期
  timeout: 3600
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
